using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Allgemeine Informationen �ber eine Assembly werden �ber die folgenden 
// Attribute gesteuert. �ndern Sie diese Attributwerte, um die Informationen zu �ndern,
// die mit einer Assembly verkn�pft sind.
[assembly: AssemblyCompany("Michael Kunz")]
[assembly: AssemblyCopyright("Copyright � Michael Kunz 2014")]

// This is autogenerated using a powershell script. //
[assembly: AssemblyVersion("8.0.23")]
[assembly: AssemblyFileVersion("8.0.23")]

