using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Allgemeine Informationen über eine Assembly werden über die folgenden 
// Attribute gesteuert. Ändern Sie diese Attributwerte, um die Informationen zu ändern,
// die mit einer Assembly verknüpft sind.
[assembly: AssemblyCompany("Michael Kunz")]
[assembly: AssemblyCopyright("Copyright © Michael Kunz and Artic Imaging 2024")]

// This is autogenerated using a powershell script. //
[assembly: AssemblyVersion("12.4.56")]
[assembly: AssemblyFileVersion("12.4.56")]

